### ISSUE TITLE
Transfer encoding request or response issue

### ISSUE THREAD

**Issue by gopisraj14** [Corvusoft/restbed#74]
Hi,

Transfer request and response will not maintain the original format of text.

Please let me know the procedure to retain the original format of text(file may be .txt, .bmp, .jpg, etc.,)

Regards,

Gopi S

**Comment by ben-crowhurst** [comment]
Please present your service and client code for examination.  My initial guess is that you fail to remove the length\r\n from the response stream. It's hard to tell with out seeing your code base.

**Comment by gopisraj14** [comment]
Hi,

  Thank you for your email.

Please find the attached sample code.

My requirement:   I need upload or download any type of file using RESTBED
service (file types: .txt, .jpg, .png, .zip etc.,)

Regards,

Gopi S

**Comment by ben-crowhurst** [comment]
@gopisraj14, I can't see the attachment?  Please submit your code via the [issue tracker](https://github.com/Corvusoft/restbed/issues/74#)

**Comment by gopisraj14** [comment]
Hi Ben,

  I am unable to upload the code in github.

shared the code to info@corvusoft.co.uk email.

Regards,

Gopi S

**Comment by callum-kirby** [comment]
@gopisraj14 I'm afraid I can't download and open the supplied attachment via info@coruvsoft.co.uk, due to our security policies.   What issues are you having specifically with presenting your code on this form?

I can help you with any issues you maybe having via GitHub.  Alternatively please see the Transfer-Encoding examples [request](https://github.com/Corvusoft/restbed/blob/master/example/transfer_encoding_request/source/example.cpp) and [response](https://github.com/Corvusoft/restbed/blob/master/example/transfer_encoding_response/source/example.cpp).

**Documentation**
[RFC Section 3.6](https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.6)
[Wikipedia Transfer Encoding](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol)

**Comment by gopisraj14** [comment]
Hi,

  The sample request and response code itself not maintaining format,
 Please check it.

Regards,

Gopi S

**Comment by callum-kirby** [comment]
In what way is it not maintaining the format?  Please provide more details than "It's not working".

**Comment by ben-crowhurst** [comment]
@gopisraj14 Do you have an email address I can contact you privately? @tataelxsi.co.in?

**Comment by gopisraj14** [comment]
The resoucee file called request.txt is formatted file when we stream the
content to server  -- at the server end its not displaying in original
format.

**Comment by callum-kirby** [comment]
The error must be in code you have written.  Both examples in the source tree work as expected.

Until you post code on Github there is really little else I can do to assist you.

**Comment by gopisraj14** [comment]
Hi,

  I have attached code.  download.txt and upload.txt are cpp files,  please rename it to .cpp

Please help me on it


[request.txt](https://github.com/Corvusoft/restbed/files/147883/request.txt)
[download.txt](https://github.com/Corvusoft/restbed/files/147885/download.txt)
[upload.txt](https://github.com/Corvusoft/restbed/files/147884/upload.txt)

**Comment by ben-crowhurst** [comment]
OK I think I can see the issue.  So let me just clarify a few points.

1. What are you building?
2. Is this homework or for work?
3. Are you attempting to request a file an then stream its contents back to the client?

**Comment by gopisraj14** [comment]
Hi,

  I am working on one product development (still doing some research).

requirement:

  I need to upload a file to server and download from the server (any
format files like .txt, .zip, .png, .jpg etc.,)

Regards,

Gopi S

**Comment by ben-crowhurst** [comment]
@gopisraj14 Thanks for that.  Could you possibly confirm the name of your employer before I highlight the major issues?

**Comment by gopisraj14** [comment]
HI,  I am working for ComX Technologies India private limited.  www.comxtech.com

Regards,

Gopi S

**Comment by ben-crowhurst** [comment]
@gopisraj14 Thanks for that information.

The first major issue is that the HTTP Request/Response cycle only expects a single status code returned (certain areas do violate this, for example HTTP header Expect: 100-Continue). Yet in your Response post_method_handler you yield OK repeatedly and then call close with an OK  status again.  

Please see [RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616.html) for HTTP specification details.

Due to the condition of the supplied code it would be far easier to rewrite it for you from the ground up than explain all of the errors.  This will take several hours and the office won't be open again until Monday.  I'll look to have someone respond with a working example next week at some point.

Enjoy your weekend.

**Comment by ben-crowhurst** [comment]
@gopisraj14 Trying to send you Transfer-Encoding code examples via gopisraj14@comxtech.com and gopisraj@comxtech.com but I keep getting reject?

**Comment by ben-crowhurst** [comment]
Gopi Sundar Raj please provide me with a private email so we may discuss what is going on here.

**Comment by gopisraj14** [comment]
please send it to gopi@comxtech.com
